# Name: Max Halbert
# Date: 3/23/2020
# Title: Makefile
# Description: This Makefile is  used to compile Lab3 programs

# Three programs for lab 3 step 1, 2 and 3
all:	lab3a	lab3b	lab3c

# Compile lab3a program for step 1
lab3a:	lab3a.c
	
	gcc -o lab3a lab3a.c -Wall -Werror

# compile lab3b program for step 2
lab3b: lab3b.c

	gcc -o lab3b lab3b.c -Wall -Werror
	
# compile lab3c program for step 3
lab3c: lab3c.c

	gcc -o lab3c lab3c.c -Wall -Werror

# Clean up all the executables of lab3
clean:

	rm -f lab3?